#!name=Unlock Bending Spoons Apps (New API)
#!desc=Support new /sign/ API

[rewrite_local]

^https:\/\/(remini|filmicpro|splice|thirtydayfitness|sleep|focos|focoslive|yoga|firstlight|doubletake|alightmotion|paperios)\.oracle\.bendingspoonsapps\.com\/v2\/(purchases\/verify\/apple|purchases\/sign\/apple|users\/setup|users\/legal)$ url script-response-body https://raw.githubusercontent.com/blackcatxhan/QX-M/main/Scripts/bendingspoonsapps.js

^https:\/\/us-central1-alight-creative\.cloudfunctions\.net\/getAccountStatusAndLicenses$ url script-response-body https://raw.githubusercontent.com/blackcatxhan/QX-M/main/Scripts/bendingspoonsapps.js


[mitm]
hostname = *.oracle.bendingspoonsapps.com, us-central1-alight-creative.cloudfunctions.net
